'use strict';

const EN = {
  paused: 'PAUSED',
  chip: 'LINUX · STILL SPIKING',
  trigger: 'MENU',
  nav: {
    continue: 'Continue',
    restart: 'Restart Match',
    match: 'Match Settings',
    controls: 'Controls',
    audio: 'Audio & Graphics',
    language: 'Language',
    about: 'About',
    quit: 'Quit',
  },
  continue: {
    kicker: 'MATCH',
    title: 'Back to the rally?',
    body: 'Resume the exact match, score and settings currently on screen.',
    poster: 'KEEP THE RALLY GOING',
  },
  restart: {
    kicker: 'MATCH',
    title: 'Restart Match',
    body: 'Start the current matchup again while keeping your selected options.',
    warning: 'Score and round progress will be cleared.',
    action: 'Restart now',
  },
  match: {
    kicker: 'GAMEPLAY',
    title: 'Match Settings',
    body: 'Real settings. No decorative switches pretending to have a job.',
    winningScore: 'Winning Score',
    speed: 'Game Speed',
    practice: 'Practice Mode',
    reset: 'Reset defaults',
  },
  controls: {
    kicker: 'INPUT',
    title: 'Controls',
    body: 'Select an action and press the key you want. Defaults can be restored at any time.',
    player1: 'PLAYER 1',
    player2: 'PLAYER 2',
    move: 'Move',
    jumpDown: 'Jump / Down',
    powerHit: 'Power Hit',
    pause: 'Pause menu',
    practiceReset: 'Practice reset',
  },
  audio: {
    kicker: 'PRESENTATION',
    title: 'Audio & Graphics',
    body: 'Original character, fewer reasons to open an operating-system menu.',
    graphics: 'Graphics',
    bgm: 'BGM',
    sfx: 'SFX',
  },
  language: {
    kicker: 'LOCALE',
    title: 'Language',
    body: 'Choose with the mouse, or press Select and use the arrow keys.',
    current: 'Current language',
    restartWarning: 'Changing language reloads the application and restarts the current match.',
  },
  about: {
    kicker: 'VERSION 2.0',
    title: 'A perfectly reasonable amount of engineering',
    body: 'Pikachu Volleyball never had a proper Linux desktop edition, so Santiago Rodríguez gave it an AppImage, a modern interface and—because restraint is apparently optional—a 2.0 roadmap.',
    original: '<strong>Pikachu Volleyball (1997)</strong> — SACHI SOFT / SAWAYAKAN Programmers and Satoshi Takenouchi. Thanks for creating the wonderfully unnecessary classic that started everything.',
    reverse: '<a href="https://github.com/gorisanson/pikachu-volleyball" target="_blank" rel="noopener"><strong>JavaScript reverse-engineering reimplementation</strong></a> — Kyutae Lee. Thanks for the painstaking work that made this Linux edition possible.',
    fork: 'Linux/AppImage implementation and 2.0 direction: Santiago Rodríguez.',
    website: 'Visit santiagorodriguez.com',
    source: 'View source on GitHub',
    punchline: 'Two electric mice. One volleyball. Linux was overdue.',
  },
  quit: {
    kicker: 'DESKTOP',
    title: 'Quit Game',
    body: 'Close the AppImage and return to a world with fewer airborne Pikachus.',
    warning: 'The current match will end.',
    action: 'Quit now',
  },
  confirmation: {
    title: 'Are you sure?',
    accept: 'Confirm',
    cancel: 'Cancel',
  },
  hints: {
    navigate: 'Navigate',
    select: 'Select',
    back: 'Back',
    change: 'Change',
    returnToMenu: 'Return to menu',
  },
  status: {
    ready: 'Game paused. Choose an action.',
    resumed: 'Match resumed.',
    restarted: 'Match restarted.',
    changed: 'Setting applied.',
    defaults: 'Default settings restored.',
    currentLanguage: 'That language is already active.',
    practiceScore: 'Winning score is unavailable while Practice Mode is on.',
    scoreReached: 'That winning score has already been reached in this match.',
    quitUnavailable: 'Quit is available only in the desktop AppImage.',
  },
  values: {
    on: 'ON',
    off: 'OFF',
    sharp: 'SHARP',
    soft: 'SOFT',
    stereo: 'STEREO',
    mono: 'MONO',
    slow: 'SLOW',
    medium: 'MEDIUM',
    fast: 'FAST',
    points: 'PTS',
  },
};

const ES = {
  ...EN,
  paused: 'PAUSA',
  chip: 'LINUX · TODAVÍA REMATANDO',
  trigger: 'MENÚ',
  nav: {
    continue: 'Continuar',
    restart: 'Reiniciar partido',
    match: 'Configuración',
    controls: 'Controles',
    audio: 'Audio y gráficos',
    language: 'Idioma',
    about: 'Acerca de',
    quit: 'Salir',
  },
  continue: {
    kicker: 'PARTIDO',
    title: '¿Volvemos al rally?',
    body: 'Retoma exactamente el partido, el puntaje y la configuración actual.',
    poster: 'QUE SIGA EL RALLY',
  },
  restart: {
    kicker: 'PARTIDO',
    title: 'Reiniciar partido',
    body: 'Empezá de nuevo con los mismos jugadores y opciones.',
    warning: 'Se borrarán el puntaje y el progreso de la ronda.',
    action: 'Reiniciar ahora',
  },
  match: {
    kicker: 'JUGABILIDAD',
    title: 'Configuración del partido',
    body: 'Opciones reales. Ningún interruptor decorativo haciéndose el importante.',
    winningScore: 'Puntaje ganador',
    speed: 'Velocidad',
    practice: 'Modo práctica',
    reset: 'Restaurar valores',
  },
  controls: {
    kicker: 'ENTRADA',
    title: 'Controles',
    body: 'Elegí una acción y presioná la tecla que quieras. Podés restaurar los valores predeterminados cuando quieras.',
    player1: 'JUGADOR 1',
    player2: 'JUGADOR 2',
    move: 'Mover',
    jumpDown: 'Saltar / Bajar',
    powerHit: 'Golpe fuerte',
    pause: 'Menú de pausa',
    practiceReset: 'Reiniciar pelota',
  },
  audio: {
    kicker: 'PRESENTACIÓN',
    title: 'Audio y gráficos',
    body: 'El carácter original, con menos motivos para abrir menús del sistema operativo.',
    graphics: 'Gráficos',
    bgm: 'Música',
    sfx: 'Efectos',
  },
  language: {
    kicker: 'IDIOMA',
    title: 'Idioma',
    body: 'Elegí con el mouse o presioná Seleccionar y usá las flechas.',
    current: 'Idioma actual',
    restartWarning: 'Cambiar el idioma recarga la aplicación y reinicia el partido actual.',
  },
  about: {
    kicker: 'VERSIÓN 2.0',
    title: 'Una cantidad perfectamente razonable de ingeniería',
    body: 'Pikachu Volleyball nunca tuvo una edición de escritorio digna para Linux, así que Santiago Rodríguez le dio un AppImage, una interfaz moderna y —porque la moderación parece opcional— una hoja de ruta 2.0.',
    original: '<strong>Pikachu Volleyball (1997)</strong> — SACHI SOFT / SAWAYAKAN Programmers y Satoshi Takenouchi. Gracias por crear el clásico maravillosamente innecesario que empezó todo.',
    reverse: '<a href="https://github.com/gorisanson/pikachu-volleyball" target="_blank" rel="noopener"><strong>Reimplementación en JavaScript mediante ingeniería inversa</strong></a> — Kyutae Lee. Gracias por el trabajo minucioso que hizo posible esta edición para Linux.',
    fork: 'Implementación Linux/AppImage y dirección de 2.0: Santiago Rodríguez.',
    website: 'Visitar santiagorodriguez.com',
    source: 'Ver código en GitHub',
    punchline: 'Dos ratones eléctricos. Una pelota. Linux ya estaba tardando.',
  },
  quit: {
    kicker: 'ESCRITORIO',
    title: 'Salir del juego',
    body: 'Cierra el AppImage y vuelve a un mundo con menos Pikachus voladores.',
    warning: 'El partido actual terminará.',
    action: 'Salir ahora',
  },
  confirmation: { title: '¿Confirmás?', accept: 'Confirmar', cancel: 'Cancelar' },
  hints: { navigate: 'Navegar', select: 'Seleccionar', back: 'Volver', change: 'Cambiar', returnToMenu: 'Volver al menú' },
  status: {
    ...EN.status,
    ready: 'Juego en pausa. Elegí una acción.',
    resumed: 'Partido reanudado.',
    restarted: 'Partido reiniciado.',
    changed: 'Configuración aplicada.',
    defaults: 'Valores predeterminados restaurados.',
    currentLanguage: 'Ese idioma ya está activo.',
    practiceScore: 'El puntaje ganador no se usa en modo práctica.',
    scoreReached: 'Ese puntaje ganador ya fue alcanzado en este partido.',
    quitUnavailable: 'Salir sólo está disponible en el AppImage de escritorio.',
  },
};

const KO = {
  ...EN,
  paused: '일시 정지',
  chip: 'LINUX · 아직도 스파이크 중',
  trigger: '메뉴',
  nav: { continue: '계속', restart: '경기 다시 시작', match: '경기 설정', controls: '조작', audio: '오디오 및 그래픽', language: '언어', about: '정보', quit: '종료' },
  continue: { kicker: '경기', title: '랠리로 돌아갈까요?', body: '현재 점수와 설정 그대로 경기를 이어갑니다.', poster: '랠리를 계속하세요' },
  restart: { kicker: '경기', title: '경기 다시 시작', body: '선택한 옵션을 유지한 채 현재 대전을 처음부터 시작합니다.', warning: '점수와 라운드 진행 상황이 초기화됩니다.', action: '지금 다시 시작' },
  match: { kicker: '게임플레이', title: '경기 설정', body: '실제로 적용되는 설정입니다. 장식용 스위치는 없습니다.', winningScore: '승리 점수', speed: '게임 속도', practice: '연습 모드', reset: '기본값 복원' },
  controls: { kicker: '입력', title: '조작', body: '동작을 선택하고 원하는 키를 누르세요. 언제든 기본 설정으로 되돌릴 수 있습니다.', player1: '플레이어 1', player2: '플레이어 2', move: '이동', jumpDown: '점프 / 아래', powerHit: '파워 히트', pause: '일시 정지 메뉴', practiceReset: '공 초기화' },
  audio: { kicker: '표현', title: '오디오 및 그래픽', body: '원작의 개성은 유지하고 운영체제 메뉴는 덜 엽니다.', graphics: '그래픽', bgm: '배경 음악', sfx: '효과음' },
  language: { kicker: '언어', title: '언어', body: '마우스로 선택하거나 선택 키를 누른 뒤 방향키를 사용하세요.', current: '현재 언어', restartWarning: '언어를 바꾸면 앱이 다시 로드되고 현재 경기가 재시작됩니다.' },
  about: { kicker: '버전 2.0', title: '아주 합리적인 수준의 엔지니어링', body: 'Pikachu Volleyball에는 제대로 된 Linux 데스크톱판이 없었습니다. 그래서 Santiago Rodríguez가 AppImage와 현대적인 인터페이스, 그리고 절제는 선택 사항이라는 듯한 2.0 로드맵을 더했습니다.', original: '<strong>Pikachu Volleyball (1997)</strong> — SACHI SOFT / SAWAYAKAN Programmers와 Satoshi Takenouchi. 이 모든 것의 시작이 된 멋지게 불필요한 고전을 만들어 주셔서 감사합니다.', reverse: '<a href="https://github.com/gorisanson/pikachu-volleyball" target="_blank" rel="noopener"><strong>JavaScript 리버스 엔지니어링 재구현</strong></a> — Kyutae Lee. 이 Linux판을 가능하게 한 세심한 작업에 감사드립니다.', fork: 'Linux/AppImage 구현 및 2.0 방향: Santiago Rodríguez.', website: 'santiagorodriguez.com 방문', source: 'GitHub 소스 보기', punchline: '전기 쥐 둘. 배구공 하나. Linux가 너무 늦었습니다.' },
  quit: { kicker: '데스크톱', title: '게임 종료', body: 'AppImage를 닫고 공중의 피카츄가 더 적은 세계로 돌아갑니다.', warning: '현재 경기가 종료됩니다.', action: '지금 종료' },
  confirmation: { title: '확실합니까?', accept: '확인', cancel: '취소' },
  hints: { navigate: '이동', select: '선택', back: '뒤로', change: '변경', returnToMenu: '메뉴로 돌아가기' },
  status: { ...EN.status, ready: '게임이 일시 정지되었습니다.', resumed: '경기를 계속합니다.', restarted: '경기를 다시 시작했습니다.', changed: '설정이 적용되었습니다.', defaults: '기본 설정을 복원했습니다.', currentLanguage: '이미 선택된 언어입니다.', practiceScore: '연습 모드에서는 승리 점수를 사용하지 않습니다.', scoreReached: '현재 경기에서 이미 그 점수에 도달했습니다.', quitUnavailable: '종료는 데스크톱 AppImage에서만 사용할 수 있습니다.' },
};

const ZH = {
  ...EN,
  paused: '已暂停',
  chip: 'LINUX · 仍在扣杀',
  trigger: '菜单',
  nav: { continue: '继续', restart: '重新开始比赛', match: '比赛设置', controls: '控制', audio: '音频与画面', language: '语言', about: '关于', quit: '退出' },
  continue: { kicker: '比赛', title: '回到对局？', body: '以当前比分和设置继续比赛。', poster: '继续回合' },
  restart: { kicker: '比赛', title: '重新开始比赛', body: '保留已选设置并重新开始当前对阵。', warning: '比分与回合进度将被清除。', action: '立即重新开始' },
  match: { kicker: '玩法', title: '比赛设置', body: '这些设置会真正生效，不再只是装饰。', winningScore: '获胜分数', speed: '游戏速度', practice: '练习模式', reset: '恢复默认值' },
  controls: { kicker: '输入', title: '控制', body: '选择一个动作并按下想要使用的按键。随时可以恢复默认设置。', player1: '玩家 1', player2: '玩家 2', move: '移动', jumpDown: '跳跃 / 下移', powerHit: '强力击球', pause: '暂停菜单', practiceReset: '重置球' },
  audio: { kicker: '表现', title: '音频与画面', body: '保留原作个性，同时少打开一些系统菜单。', graphics: '画面', bgm: '背景音乐', sfx: '音效' },
  language: { kicker: '语言', title: '语言', body: '可用鼠标选择，或按选择键后使用方向键。', current: '当前语言', restartWarning: '切换语言会重新载入应用并重新开始当前比赛。' },
  about: { kicker: '版本 2.0', title: '完全合理的工程投入', body: 'Pikachu Volleyball 一直没有真正的 Linux 桌面版，于是 Santiago Rodríguez 为它补上了 AppImage、现代界面，以及一份仿佛“适可而止”并不存在的 2.0 路线图。', original: '<strong>Pikachu Volleyball (1997)</strong> — SACHI SOFT / SAWAYAKAN Programmers 与 Satoshi Takenouchi。感谢你们创造了这个精彩又毫无必要的经典，一切由此开始。', reverse: '<a href="https://github.com/gorisanson/pikachu-volleyball" target="_blank" rel="noopener"><strong>JavaScript 逆向工程重实现</strong></a> — Kyutae Lee。感谢这项细致工作，让这个 Linux 版本成为可能。', fork: 'Linux/AppImage 实现与 2.0 方向：Santiago Rodríguez。', website: '访问 santiagorodriguez.com', source: '在 GitHub 查看源码', punchline: '两只电气鼠，一只排球。Linux 早该有了。' },
  quit: { kicker: '桌面', title: '退出游戏', body: '关闭 AppImage，回到空中皮卡丘更少的世界。', warning: '当前比赛将结束。', action: '立即退出' },
  confirmation: { title: '确定吗？', accept: '确认', cancel: '取消' },
  hints: { navigate: '导航', select: '选择', back: '返回', change: '更改', returnToMenu: '返回菜单' },
  status: { ...EN.status, ready: '游戏已暂停，请选择操作。', resumed: '比赛已继续。', restarted: '比赛已重新开始。', changed: '设置已应用。', defaults: '已恢复默认设置。', currentLanguage: '该语言已经启用。', practiceScore: '练习模式下不使用获胜分数。', scoreReached: '当前比赛已经达到该分数。', quitUnavailable: '退出功能仅在桌面 AppImage 中可用。' },
};

const CONTROL_ACTIONS_EN = Object.freeze({
  'p1.left': 'Move left',
  'p1.right': 'Move right',
  'p1.up': 'Jump',
  'p1.down': 'Move down',
  'p1.downRight': 'Down-right shortcut',
  'p1.powerPrimary': 'Power Hit · primary',
  'p1.powerAlternate': 'Power Hit · alternate',
  'p2.left': 'Move left',
  'p2.right': 'Move right',
  'p2.up': 'Jump',
  'p2.down': 'Move down',
  'p2.powerPrimary': 'Power Hit · primary',
  'p2.powerAlternate': 'Power Hit · alternate',
});

const CONTROL_ACTIONS_KO = Object.freeze({
  'p1.left': '왼쪽 이동',
  'p1.right': '오른쪽 이동',
  'p1.up': '점프',
  'p1.down': '아래 이동',
  'p1.downRight': '오른쪽 아래 단축키',
  'p1.powerPrimary': '파워 히트 · 기본',
  'p1.powerAlternate': '파워 히트 · 보조',
  'p2.left': '왼쪽 이동',
  'p2.right': '오른쪽 이동',
  'p2.up': '점프',
  'p2.down': '아래 이동',
  'p2.powerPrimary': '파워 히트 · 기본',
  'p2.powerAlternate': '파워 히트 · 보조',
});

const CONTROL_ACTIONS_ZH = Object.freeze({
  'p1.left': '向左移动',
  'p1.right': '向右移动',
  'p1.up': '跳跃',
  'p1.down': '向下移动',
  'p1.downRight': '右下快捷键',
  'p1.powerPrimary': '强力击球 · 主键',
  'p1.powerAlternate': '强力击球 · 备用键',
  'p2.left': '向左移动',
  'p2.right': '向右移动',
  'p2.up': '跳跃',
  'p2.down': '向下移动',
  'p2.powerPrimary': '强力击球 · 主键',
  'p2.powerAlternate': '强力击球 · 备用键',
});

const CONTROL_EDITOR = Object.freeze({
  en: {
    actions: CONTROL_ACTIONS_EN,
    change: 'Change',
    resetPlayer1: 'Reset Player 1',
    resetPlayer2: 'Reset Player 2',
    resetAll: 'Reset all controls',
    captureTitle: 'Press a new key',
    captureBody: 'Choose a key for {action}. Escape cancels.',
    proposedTitle: 'Confirm new control',
    proposedBody: 'Use {key} for {action}?',
    reserved: 'That key is reserved for pause, back, or practice reset.',
    conflict: 'That key is already assigned to {action}.',
    saved: 'Control updated.',
    resetDone: 'Control defaults restored.',
  },
  'es-ar': {
    actions: {
      'p1.left': 'Mover a la izquierda',
      'p1.right': 'Mover a la derecha',
      'p1.up': 'Saltar',
      'p1.down': 'Bajar',
      'p1.downRight': 'Atajo abajo-derecha',
      'p1.powerPrimary': 'Golpe fuerte · principal',
      'p1.powerAlternate': 'Golpe fuerte · alternativo',
      'p2.left': 'Mover a la izquierda',
      'p2.right': 'Mover a la derecha',
      'p2.up': 'Saltar',
      'p2.down': 'Bajar',
      'p2.powerPrimary': 'Golpe fuerte · principal',
      'p2.powerAlternate': 'Golpe fuerte · alternativo',
    },
    change: 'Cambiar',
    resetPlayer1: 'Restaurar Jugador 1',
    resetPlayer2: 'Restaurar Jugador 2',
    resetAll: 'Restaurar todos',
    captureTitle: 'Presioná una tecla nueva',
    captureBody: 'Elegí una tecla para {action}. Escape cancela.',
    proposedTitle: 'Confirmar control',
    proposedBody: '¿Usar {key} para {action}?',
    reserved:
      'Esa tecla está reservada para pausa, volver o reiniciar la pelota.',
    conflict: 'Esa tecla ya está asignada a {action}.',
    saved: 'Control actualizado.',
    resetDone: 'Controles predeterminados restaurados.',
  },
  ko: {
    actions: CONTROL_ACTIONS_KO,
    change: '키 변경',
    resetPlayer1: '플레이어 1 초기화',
    resetPlayer2: '플레이어 2 초기화',
    resetAll: '모든 조작 초기화',
    captureTitle: '새 키를 누르세요',
    captureBody: '{action}에 사용할 키를 누르세요. Escape로 취소합니다.',
    proposedTitle: '새 조작 확인',
    proposedBody: '{action}에 {key} 키를 사용하시겠습니까?',
    reserved: '일시 정지, 뒤로 가기 또는 공 초기화에 예약된 키입니다.',
    conflict: '이미 {action}에 할당된 키입니다.',
    saved: '조작 키가 변경되었습니다.',
    resetDone: '기본 조작을 복원했습니다.',
  },
  zh: {
    actions: CONTROL_ACTIONS_ZH,
    change: '更改',
    resetPlayer1: '重置玩家 1',
    resetPlayer2: '重置玩家 2',
    resetAll: '重置全部控制',
    captureTitle: '按下新按键',
    captureBody: '为 {action} 选择按键。按 Escape 取消。',
    proposedTitle: '确认新控制',
    proposedBody: '将 {key} 用于 {action}？',
    reserved: '该按键已保留给暂停、返回或重置球。',
    conflict: '该按键已分配给 {action}。',
    saved: '控制已更新。',
    resetDone: '已恢复默认控制。',
  },
  ca: {
    actions: {
      'p1.left': 'Moure’s a l’esquerra',
      'p1.right': 'Moure’s a la dreta',
      'p1.up': 'Saltar',
      'p1.down': 'Baixar',
      'p1.downRight': 'Drecera avall-dreta',
      'p1.powerPrimary': 'Cop potent · principal',
      'p1.powerAlternate': 'Cop potent · alternatiu',
      'p2.left': 'Moure’s a l’esquerra',
      'p2.right': 'Moure’s a la dreta',
      'p2.up': 'Saltar',
      'p2.down': 'Baixar',
      'p2.powerPrimary': 'Cop potent · principal',
      'p2.powerAlternate': 'Cop potent · alternatiu',
    },
    change: 'Canviar',
    resetPlayer1: 'Restablir Jugador 1',
    resetPlayer2: 'Restablir Jugador 2',
    resetAll: 'Restablir tots els controls',
    captureTitle: 'Prem una tecla nova',
    captureBody: 'Tria una tecla per a {action}. Escape cancel·la.',
    proposedTitle: 'Confirma el control',
    proposedBody: 'Vols usar {key} per a {action}?',
    reserved:
      'Aquesta tecla està reservada per a pausa, tornar o reiniciar la pilota.',
    conflict: 'Aquesta tecla ja està assignada a {action}.',
    saved: 'Control actualitzat.',
    resetDone: 'Controls predeterminats restaurats.',
  },
});

const ABOUT_COPY = Object.freeze({
  en: {
    kicker: 'LINUX EDITION',
    title: 'One more match, years later',
    body:
      'As a child, this game meant a great deal to me. Simple, joyful, hard-to-put-down games like this became part of my doorway into the Pokémon world—and the beginning of an affection that never really left.',
    original:
      '<strong>Pikachu Volleyball (1997)</strong> — SACHI SOFT / SAWAYAKAN Programmers and Satoshi Takenouchi. Thanks for creating the small, unforgettable classic that started it all.',
    reverse:
      '<a href="https://github.com/gorisanson/pikachu-volleyball" target="_blank" rel="noopener"><strong>JavaScript reverse-engineering reimplementation</strong></a> — Kyutae Lee. Thanks for the painstaking work that kept the game alive on the web and made this edition possible.',
    fork: 'This edition is simply my way of caring for a game I remember fondly.',
    website: 'Visit santiagorodriguez.com',
    source: 'View source on GitHub',
    punchline: 'Some childhood games always deserve one more match.',
  },
  'es-ar': {
    kicker: 'EDICIÓN LINUX',
    title: 'Un partido más, tantos años después',
    body:
      'De chico, este juego me hacía mucha ilusión. Juegos sencillos, alegres y difíciles de soltar como este fueron parte de mi puerta de entrada al universo Pokémon y el comienzo de un cariño que todavía conservo.',
    original:
      '<strong>Pikachu Volleyball (1997)</strong> — SACHI SOFT / SAWAYAKAN Programmers y Satoshi Takenouchi. Gracias por crear el pequeño e inolvidable clásico que empezó todo.',
    reverse:
      '<a href="https://github.com/gorisanson/pikachu-volleyball" target="_blank" rel="noopener"><strong>Reimplementación en JavaScript mediante ingeniería inversa</strong></a> — Kyutae Lee. Gracias por el trabajo minucioso que mantuvo vivo el juego en la web e hizo posible esta edición.',
    fork: 'Esta edición es, simplemente, mi manera de cuidar un juego que recuerdo con mucho cariño.',
    website: 'Visitar santiagorodriguez.com',
    source: 'Ver código en GitHub',
    punchline: 'Hay juegos de la infancia que siempre merecen un partido más.',
  },
  ko: {
    kicker: 'LINUX 에디션',
    title: '세월이 흘러도, 한 경기 더',
    body:
      '어릴 적 이 게임은 제게 큰 설렘이었습니다. 이처럼 단순하지만 즐겁고 좀처럼 손을 놓기 힘든 게임들은 포켓몬 세계로 들어가는 문이 되었고, 지금까지 이어지는 애정의 시작이 되었습니다.',
    original:
      '<strong>Pikachu Volleyball (1997)</strong> — SACHI SOFT / SAWAYAKAN Programmers와 Satoshi Takenouchi. 이 모든 것의 시작이 된 작지만 잊을 수 없는 고전을 만들어 주셔서 감사합니다.',
    reverse:
      '<a href="https://github.com/gorisanson/pikachu-volleyball" target="_blank" rel="noopener"><strong>JavaScript 리버스 엔지니어링 재구현</strong></a> — Kyutae Lee. 웹에서 이 게임을 이어 가고 이번 에디션을 가능하게 한 세심한 작업에 감사드립니다.',
    fork: '이 에디션은 좋은 추억으로 간직한 게임을 조심스럽게 돌보는 저만의 작은 방식일 뿐입니다.',
    website: 'santiagorodriguez.com 방문',
    source: 'GitHub 소스 보기',
    punchline: '어린 시절의 어떤 게임은 언제나 한 경기를 더 할 가치가 있습니다.',
  },
  zh: {
    kicker: 'LINUX 版本',
    title: '多年以后，再来一局',
    body:
      '小时候，这款游戏曾让我满怀期待。这类简单、快乐又让人舍不得放下的游戏，成了我走进宝可梦世界的入口，也开启了一份延续至今的喜爱。',
    original:
      '<strong>Pikachu Volleyball (1997)</strong> — SACHI SOFT / SAWAYAKAN Programmers 与 Satoshi Takenouchi。感谢你们创造了这个小巧却令人难忘的经典，一切由此开始。',
    reverse:
      '<a href="https://github.com/gorisanson/pikachu-volleyball" target="_blank" rel="noopener"><strong>JavaScript 逆向工程重实现</strong></a> — Kyutae Lee。感谢这项细致工作，让游戏在网页上延续，也让这个版本成为可能。',
    fork: '这个版本只是我珍惜一款童年游戏、认真照看它的一种方式。',
    website: '访问 santiagorodriguez.com',
    source: '在 GitHub 查看源码',
    punchline: '有些童年游戏，总值得再来一局。',
  },
  ca: {
    kicker: 'EDICIÓ LINUX',
    title: 'Un partit més, tants anys després',
    body:
      'De petit, aquest joc em feia molta il·lusió. Jocs senzills, alegres i difícils de deixar com aquest van ser part de la meva porta d’entrada a l’univers Pokémon i l’inici d’un afecte que encara conservo.',
    original:
      '<strong>Pikachu Volleyball (1997)</strong> — SACHI SOFT / SAWAYAKAN Programmers i Satoshi Takenouchi. Gràcies per crear el petit clàssic inoblidable que ho va començar tot.',
    reverse:
      '<a href="https://github.com/gorisanson/pikachu-volleyball" target="_blank" rel="noopener"><strong>Reimplementació JavaScript mitjançant enginyeria inversa</strong></a> — Kyutae Lee. Gràcies per la feina minuciosa que va mantenir el joc viu al web i va fer possible aquesta edició.',
    fork: 'Aquesta edició és, simplement, la meva manera de cuidar un joc que recordo amb molt d’afecte.',
    website: 'Visita santiagorodriguez.com',
    source: 'Veure el codi a GitHub',
    punchline: 'Hi ha jocs de la infància que sempre mereixen un partit més.',
  },
});

const CATALAN = Object.freeze({
  paused: 'EN PAUSA',
  chip: 'LINUX · ENCARA REMATANT',
  trigger: 'MENÚ',
  nav: {
    continue: 'Continuar',
    restart: 'Reiniciar el partit',
    match: 'Configuració del partit',
    controls: 'Controls',
    audio: 'Àudio i gràfics',
    language: 'Idioma',
    about: 'Quant al joc',
    quit: 'Sortir',
  },
  continue: {
    kicker: 'PARTIT',
    title: 'Tornem al ral·li?',
    body: 'Continua exactament el partit, el marcador i la configuració actuals.',
    poster: 'QUE CONTINUÏ EL RAL·LI',
  },
  restart: {
    kicker: 'PARTIT',
    title: 'Reiniciar el partit',
    body: 'Comença de nou amb els mateixos jugadors i opcions.',
    warning: 'S’esborraran el marcador i el progrés de la ronda.',
    action: 'Reiniciar ara',
  },
  match: {
    kicker: 'JUGABILITAT',
    title: 'Configuració del partit',
    body: 'Opcions reals. Cap interruptor decoratiu fingint que treballa.',
    winningScore: 'Puntuació guanyadora',
    speed: 'Velocitat',
    practice: 'Mode pràctica',
    reset: 'Restablir valors',
  },
  controls: {
    kicker: 'ENTRADA',
    title: 'Controls',
    body:
      'Selecciona una acció i prem la tecla que vulguis. Els valors predeterminats continuen sent una bona idea.',
    player1: 'JUGADOR 1',
    player2: 'JUGADOR 2',
    move: 'Moure',
    jumpDown: 'Saltar / Baixar',
    powerHit: 'Cop potent',
    pause: 'Menú de pausa',
    practiceReset: 'Reiniciar la pilota',
  },
  audio: {
    kicker: 'PRESENTACIÓ',
    title: 'Àudio i gràfics',
    body:
      'El caràcter original, amb menys motius per obrir menús del sistema operatiu.',
    graphics: 'Gràfics',
    bgm: 'Música',
    sfx: 'Efectes',
  },
  language: {
    kicker: 'IDIOMA',
    title: 'Idioma',
    body: 'Tria amb el ratolí o prem Seleccionar i usa les fletxes.',
    current: 'Idioma actual',
    restartWarning:
      'Canviar l’idioma recarrega l’aplicació i reinicia el partit actual.',
  },
  about: ABOUT_COPY.ca,
  quit: {
    kicker: 'ESCRIPTORI',
    title: 'Sortir del joc',
    body: 'Tanca l’AppImage i torna a un món amb menys Pikachus volant.',
    warning: 'El partit actual acabarà.',
    action: 'Sortir ara',
  },
  confirmation: {
    title: 'N’estàs segur?',
    accept: 'Confirmar',
    cancel: 'Cancel·lar',
  },
  hints: {
    navigate: 'Navegar',
    select: 'Seleccionar',
    back: 'Tornar',
    change: 'Canviar',
    returnToMenu: 'Tornar al menú',
  },
  status: {
    ready: 'Joc en pausa. Tria una acció.',
    resumed: 'Partit reprès.',
    restarted: 'Partit reiniciat.',
    changed: 'Configuració aplicada.',
    defaults: 'Valors predeterminats restaurats.',
    currentLanguage: 'Aquest idioma ja està actiu.',
    practiceScore:
      'La puntuació guanyadora no s’utilitza en mode pràctica.',
    scoreReached: 'Aquesta puntuació ja s’ha assolit en el partit.',
    quitUnavailable:
      'Sortir només està disponible a l’AppImage d’escriptori.',
  },
  values: {
    on: 'ACTIVAT',
    off: 'DESACTIVAT',
    sharp: 'NÍTID',
    soft: 'SUAU',
    stereo: 'ESTÈREO',
    mono: 'MONO',
    slow: 'LENTA',
    medium: 'MITJANA',
    fast: 'RÀPIDA',
    points: 'PTS',
  },
});

const THEME_COPY = Object.freeze({
  en: { label: 'Interface Theme', light: 'LIGHT', dark: 'DARK' },
  'es-ar': { label: 'Tema de interfaz', light: 'CLARO', dark: 'OSCURO' },
  ca: { label: 'Tema de la interfície', light: 'CLAR', dark: 'FOSC' },
  ko: { label: '인터페이스 테마', light: '라이트', dark: '다크' },
  zh: { label: '界面主题', light: '浅色', dark: '深色' },
});

const BASE_STRINGS = Object.freeze({ en: EN, 'es-ar': ES, ko: KO, zh: ZH });

function composeMenuStrings(locale, baseStrings) {
  const editor = CONTROL_EDITOR[locale] || CONTROL_EDITOR.en;
  const about = ABOUT_COPY[locale] || ABOUT_COPY.en;
  if (locale === 'ca') {
    return {
      ...baseStrings,
      ...CATALAN,
      about,
      controls: { ...CATALAN.controls, ...editor },
    };
  }
  return {
    ...baseStrings,
    about,
    controls: { ...baseStrings.controls, ...editor },
  };
}

export function getIntegratedMenuStrings(locale) {
  const baseStrings = BASE_STRINGS[locale] || EN;
  return {
    ...composeMenuStrings(locale, baseStrings),
    theme: THEME_COPY[locale] || THEME_COPY.en,
  };
}
