'use strict';

const CONTROL_ACTIONS_EN = Object.freeze({
  'p1.left': 'Move left',
  'p1.right': 'Move right',
  'p1.up': 'Jump',
  'p1.down': 'Move down',
  'p1.downRight': 'Down-right shortcut',
  'p1.powerPrimary': 'Power Hit · primary',
  'p1.powerAlternate': 'Power Hit · alternate',
  'p2.left': 'Move left',
  'p2.right': 'Move right',
  'p2.up': 'Jump',
  'p2.down': 'Move down',
  'p2.powerPrimary': 'Power Hit · primary',
  'p2.powerAlternate': 'Power Hit · alternate',
});

const CONTROL_EDITOR = Object.freeze({
  en: {
    actions: CONTROL_ACTIONS_EN,
    change: 'Change',
    resetPlayer1: 'Reset Player 1',
    resetPlayer2: 'Reset Player 2',
    resetAll: 'Reset all controls',
    captureTitle: 'Press a new key',
    captureBody: 'Choose a key for {action}. Escape cancels.',
    proposedTitle: 'Confirm new control',
    proposedBody: 'Use {key} for {action}?',
    reserved: 'That key is reserved for pause, back, or practice reset.',
    conflict: 'That key is already assigned to {action}.',
    saved: 'Control updated.',
    resetDone: 'Control defaults restored.',
  },
  'es-ar': {
    actions: {
      'p1.left': 'Mover a la izquierda',
      'p1.right': 'Mover a la derecha',
      'p1.up': 'Saltar',
      'p1.down': 'Bajar',
      'p1.downRight': 'Atajo abajo-derecha',
      'p1.powerPrimary': 'Golpe fuerte · principal',
      'p1.powerAlternate': 'Golpe fuerte · alternativo',
      'p2.left': 'Mover a la izquierda',
      'p2.right': 'Mover a la derecha',
      'p2.up': 'Saltar',
      'p2.down': 'Bajar',
      'p2.powerPrimary': 'Golpe fuerte · principal',
      'p2.powerAlternate': 'Golpe fuerte · alternativo',
    },
    change: 'Cambiar',
    resetPlayer1: 'Restaurar Jugador 1',
    resetPlayer2: 'Restaurar Jugador 2',
    resetAll: 'Restaurar todos',
    captureTitle: 'Presioná una tecla nueva',
    captureBody: 'Elegí una tecla para {action}. Escape cancela.',
    proposedTitle: 'Confirmar control',
    proposedBody: '¿Usar {key} para {action}?',
    reserved: 'Esa tecla está reservada para pausa, volver o reiniciar la pelota.',
    conflict: 'Esa tecla ya está asignada a {action}.',
    saved: 'Control actualizado.',
    resetDone: 'Controles predeterminados restaurados.',
  },
  ko: {
    actions: CONTROL_ACTIONS_EN,
    change: '키 변경',
    resetPlayer1: '플레이어 1 초기화',
    resetPlayer2: '플레이어 2 초기화',
    resetAll: '모든 조작 초기화',
    captureTitle: '새 키를 누르세요',
    captureBody: '{action}에 사용할 키를 누르세요. Escape로 취소합니다.',
    proposedTitle: '새 조작 확인',
    proposedBody: '{action}에 {key} 키를 사용하시겠습니까?',
    reserved: '일시 정지, 뒤로 가기 또는 공 초기화에 예약된 키입니다.',
    conflict: '이미 {action}에 할당된 키입니다.',
    saved: '조작 키가 변경되었습니다.',
    resetDone: '기본 조작을 복원했습니다.',
  },
  zh: {
    actions: CONTROL_ACTIONS_EN,
    change: '更改',
    resetPlayer1: '重置玩家 1',
    resetPlayer2: '重置玩家 2',
    resetAll: '重置全部控制',
    captureTitle: '按下新按键',
    captureBody: '为 {action} 选择按键。按 Escape 取消。',
    proposedTitle: '确认新控制',
    proposedBody: '将 {key} 用于 {action}？',
    reserved: '该按键已保留给暂停、返回或重置球。',
    conflict: '该按键已分配给 {action}。',
    saved: '控制已更新。',
    resetDone: '已恢复默认控制。',
  },
  ca: {
    actions: {
      'p1.left': "Moure's a l'esquerra",
      'p1.right': 'Moure’s a la dreta',
      'p1.up': 'Saltar',
      'p1.down': 'Baixar',
      'p1.downRight': 'Drecera avall-dreta',
      'p1.powerPrimary': 'Cop potent · principal',
      'p1.powerAlternate': 'Cop potent · alternatiu',
      'p2.left': "Moure's a l'esquerra",
      'p2.right': 'Moure’s a la dreta',
      'p2.up': 'Saltar',
      'p2.down': 'Baixar',
      'p2.powerPrimary': 'Cop potent · principal',
      'p2.powerAlternate': 'Cop potent · alternatiu',
    },
    change: 'Canviar',
    resetPlayer1: 'Restablir Jugador 1',
    resetPlayer2: 'Restablir Jugador 2',
    resetAll: 'Restablir tots els controls',
    captureTitle: 'Prem una tecla nova',
    captureBody: 'Tria una tecla per a {action}. Escape cancel·la.',
    proposedTitle: 'Confirma el control',
    proposedBody: 'Vols usar {key} per a {action}?',
    reserved: 'Aquesta tecla està reservada per a pausa, tornar o reiniciar la pilota.',
    conflict: 'Aquesta tecla ja està assignada a {action}.',
    saved: 'Control actualitzat.',
    resetDone: 'Controls predeterminats restaurats.',
  },
});

const CATALAN = Object.freeze({
  paused: 'EN PAUSA',
  chip: '2.0 · ENCARA REMATANT',
  trigger: 'MENÚ',
  nav: {
    continue: 'Continuar',
    restart: 'Reiniciar el partit',
    match: 'Configuració del partit',
    controls: 'Controls',
    audio: 'Àudio i gràfics',
    language: 'Idioma',
    about: 'Quant al joc',
    quit: 'Sortir',
  },
  continue: {
    kicker: 'PARTIT',
    title: 'Tornem al ral·li?',
    body: 'Continua exactament el partit, el marcador i la configuració actuals.',
    poster: 'QUE CONTINUÏ EL RAL·LI',
  },
  restart: {
    kicker: 'PARTIT',
    title: 'Reiniciar el partit',
    body: 'Comença de nou amb els mateixos jugadors i opcions.',
    warning: 'S’esborraran el marcador i el progrés de la ronda.',
    action: 'Reiniciar ara',
  },
  match: {
    kicker: 'JUGABILITAT',
    title: 'Configuració del partit',
    body: 'Opcions reals. Cap interruptor decoratiu fingint que treballa.',
    winningScore: 'Puntuació guanyadora',
    speed: 'Velocitat',
    practice: 'Mode pràctica',
    reset: 'Restablir valors',
  },
  controls: {
    kicker: 'ENTRADA',
    title: 'Controls',
    body: 'Selecciona una acció i prem la tecla que vulguis. Els valors predeterminats continuen sent una bona idea.',
    player1: 'JUGADOR 1',
    player2: 'JUGADOR 2',
    move: 'Moure',
    jumpDown: 'Saltar / Baixar',
    powerHit: 'Cop potent',
    pause: 'Menú de pausa',
    practiceReset: 'Reiniciar la pilota',
  },
  audio: {
    kicker: 'PRESENTACIÓ',
    title: 'Àudio i gràfics',
    body: 'El caràcter original, amb menys motius per obrir menús del sistema operatiu.',
    graphics: 'Gràfics',
    bgm: 'Música',
    sfx: 'Efectes',
  },
  language: {
    kicker: 'IDIOMA',
    title: 'Idioma',
    body: 'Tria amb el ratolí o prem Seleccionar i usa les fletxes.',
    current: 'Idioma actual',
    restartWarning: 'Canviar l’idioma recarrega l’aplicació i reinicia el partit actual.',
  },
  about: {
    kicker: 'VERSIÓ 2.0',
    title: 'Una quantitat perfectament raonable d’enginyeria',
    body: 'Pikachu Volleyball no tenia una edició d’escriptori Linux com calia, així que Santiago Rodríguez li va donar un AppImage, una interfície moderna i —perquè la moderació és opcional— un full de ruta 2.0.',
    original: '<strong>Pikachu Volleyball (1997)</strong> — SACHI SOFT / SAWAYAKAN Programmers i Satoshi Takenouchi. Gràcies per crear el clàssic meravellosament innecessari que ho va començar tot.',
    reverse: '<a href="https://github.com/gorisanson/pikachu-volleyball" target="_blank" rel="noopener"><strong>Reimplementació JavaScript mitjançant enginyeria inversa</strong></a> — Kyutae Lee. Gràcies per la feina minuciosa que ha fet possible aquesta edició per a Linux.',
    fork: 'Implementació Linux/AppImage i direcció de 2.0: Santiago Rodríguez.',
    website: 'Visita santiagorodriguez.com',
    source: 'Veure el codi a GitHub',
    punchline: 'Dos ratolins elèctrics. Una pilota. Linux ja feia tard.',
  },
  quit: {
    kicker: 'ESCRIPTORI',
    title: 'Sortir del joc',
    body: 'Tanca l’AppImage i torna a un món amb menys Pikachus volant.',
    warning: 'El partit actual acabarà.',
    action: 'Sortir ara',
  },
  confirmation: {
    title: 'N’estàs segur?',
    accept: 'Confirmar',
    cancel: 'Cancel·lar',
  },
  hints: {
    navigate: 'Navegar',
    select: 'Seleccionar',
    back: 'Tornar',
    change: 'Canviar',
    returnToMenu: 'Tornar al menú',
  },
  status: {
    ready: 'Joc en pausa. Tria una acció.',
    resumed: 'Partit reprès.',
    restarted: 'Partit reiniciat.',
    changed: 'Configuració aplicada.',
    defaults: 'Valors predeterminats restaurats.',
    currentLanguage: 'Aquest idioma ja està actiu.',
    practiceScore: 'La puntuació guanyadora no s’utilitza en mode pràctica.',
    scoreReached: 'Aquesta puntuació ja s’ha assolit en el partit.',
    quitUnavailable: 'Sortir només està disponible a l’AppImage d’escriptori.',
  },
  values: {
    on: 'ACTIVAT',
    off: 'DESACTIVAT',
    sharp: 'NÍTID',
    soft: 'SUau',
    stereo: 'ESTÈREO',
    mono: 'MONO',
    slow: 'LENTA',
    medium: 'MITJANA',
    fast: 'RÀPIDA',
    points: 'PTS',
  },
});

export function getPhase3MenuStrings(locale, baseStrings) {
  const editor = CONTROL_EDITOR[locale] || CONTROL_EDITOR.en;
  if (locale === 'ca') {
    return {
      ...baseStrings,
      ...CATALAN,
      controls: { ...CATALAN.controls, ...editor },
    };
  }
  return {
    ...baseStrings,
    controls: { ...baseStrings.controls, ...editor },
  };
}
