'use strict';

const EN = {
  paused: 'PAUSED',
  chip: '2.0 · STILL SPIKING',
  trigger: 'MENU',
  nav: {
    continue: 'Continue',
    restart: 'Restart Match',
    match: 'Match Settings',
    controls: 'Controls',
    audio: 'Audio & Graphics',
    language: 'Language',
    about: 'About',
    quit: 'Quit',
  },
  continue: {
    kicker: 'MATCH',
    title: 'Back to the rally?',
    body: 'Resume the exact match, score and settings currently on screen.',
    poster: 'KEEP THE RALLY GOING',
  },
  restart: {
    kicker: 'MATCH',
    title: 'Restart Match',
    body: 'Start the current matchup again while keeping your selected options.',
    warning: 'Score and round progress will be cleared.',
    action: 'Restart now',
  },
  match: {
    kicker: 'GAMEPLAY',
    title: 'Match Settings',
    body: 'Real settings. No decorative switches pretending to have a job.',
    winningScore: 'Winning Score',
    speed: 'Game Speed',
    practice: 'Practice Mode',
    reset: 'Reset defaults',
  },
  controls: {
    kicker: 'INPUT',
    title: 'Controls',
    body: 'The current defaults are shown here. Full remapping arrives in the next phase.',
    player1: 'PLAYER 1',
    player2: 'PLAYER 2',
    move: 'Move',
    jumpDown: 'Jump / Down',
    powerHit: 'Power Hit',
    pause: 'Pause menu',
    practiceReset: 'Practice reset',
  },
  audio: {
    kicker: 'PRESENTATION',
    title: 'Audio & Graphics',
    body: 'Original character, fewer reasons to open an operating-system menu.',
    graphics: 'Graphics',
    bgm: 'BGM',
    sfx: 'SFX',
  },
  language: {
    kicker: 'LOCALE',
    title: 'Language',
    body: 'Choose with the mouse, or press Select and use the arrow keys.',
    current: 'Current language',
    restartWarning: 'Changing language reloads the application and restarts the current match.',
  },
  about: {
    kicker: 'VERSION 2.0',
    title: 'A perfectly reasonable amount of engineering',
    body: 'Born in 1997, rebuilt for the web through Kyutae Lee’s reverse engineering, and now being carefully over-engineered by Santiago Rodríguez because Pikachu beach volleyball apparently deserved a proper Linux home.',
    original: 'Original game: SACHI SOFT / SAWAYAKAN Programmers and Satoshi Takenouchi (1997).',
    reverse: 'JavaScript reverse engineering and reimplementation: Kyutae Lee.',
    fork: 'Linux/AppImage, desktop UX and 2.0 direction: Santiago Rodríguez.',
    website: 'Visit santiagorodriguez.com',
    source: 'View source on GitHub',
    punchline: 'Two electric mice. One volleyball. No sensible stopping point.',
  },
  quit: {
    kicker: 'DESKTOP',
    title: 'Quit Game',
    body: 'Close the AppImage and return to a world with fewer airborne Pikachus.',
    warning: 'The current match will end.',
    action: 'Quit now',
  },
  confirmation: {
    title: 'Are you sure?',
    accept: 'Confirm',
    cancel: 'Cancel',
  },
  hints: {
    navigate: 'Navigate',
    select: 'Select',
    back: 'Back',
    change: 'Change',
    returnToMenu: 'Return to menu',
  },
  status: {
    ready: 'Game paused. Choose an action.',
    resumed: 'Match resumed.',
    restarted: 'Match restarted.',
    changed: 'Setting applied.',
    defaults: 'Default settings restored.',
    currentLanguage: 'That language is already active.',
    practiceScore: 'Winning score is unavailable while Practice Mode is on.',
    scoreReached: 'That winning score has already been reached in this match.',
    quitUnavailable: 'Quit is available only in the desktop AppImage.',
  },
  values: {
    on: 'ON',
    off: 'OFF',
    sharp: 'SHARP',
    soft: 'SOFT',
    stereo: 'STEREO',
    mono: 'MONO',
    slow: 'SLOW',
    medium: 'MEDIUM',
    fast: 'FAST',
    points: 'PTS',
  },
};

const ES = {
  ...EN,
  paused: 'PAUSA',
  chip: '2.0 · TODAVÍA REMATANDO',
  trigger: 'MENÚ',
  nav: {
    continue: 'Continuar',
    restart: 'Reiniciar partido',
    match: 'Configuración',
    controls: 'Controles',
    audio: 'Audio y gráficos',
    language: 'Idioma',
    about: 'Acerca de',
    quit: 'Salir',
  },
  continue: {
    kicker: 'PARTIDO',
    title: '¿Volvemos al rally?',
    body: 'Retoma exactamente el partido, el puntaje y la configuración actual.',
    poster: 'QUE SIGA EL RALLY',
  },
  restart: {
    kicker: 'PARTIDO',
    title: 'Reiniciar partido',
    body: 'Empezá de nuevo con los mismos jugadores y opciones.',
    warning: 'Se borrarán el puntaje y el progreso de la ronda.',
    action: 'Reiniciar ahora',
  },
  match: {
    kicker: 'JUGABILIDAD',
    title: 'Configuración del partido',
    body: 'Opciones reales. Ningún interruptor decorativo haciéndose el importante.',
    winningScore: 'Puntaje ganador',
    speed: 'Velocidad',
    practice: 'Modo práctica',
    reset: 'Restaurar valores',
  },
  controls: {
    kicker: 'ENTRADA',
    title: 'Controles',
    body: 'Estos son los valores actuales. La edición completa llega en la próxima fase.',
    player1: 'JUGADOR 1',
    player2: 'JUGADOR 2',
    move: 'Mover',
    jumpDown: 'Saltar / Bajar',
    powerHit: 'Golpe fuerte',
    pause: 'Menú de pausa',
    practiceReset: 'Reiniciar pelota',
  },
  audio: {
    kicker: 'PRESENTACIÓN',
    title: 'Audio y gráficos',
    body: 'El carácter original, con menos motivos para abrir menús del sistema operativo.',
    graphics: 'Gráficos',
    bgm: 'Música',
    sfx: 'Efectos',
  },
  language: {
    kicker: 'IDIOMA',
    title: 'Idioma',
    body: 'Elegí con el mouse o presioná Seleccionar y usá las flechas.',
    current: 'Idioma actual',
    restartWarning: 'Cambiar el idioma recarga la aplicación y reinicia el partido actual.',
  },
  about: {
    kicker: 'VERSIÓN 2.0',
    title: 'Una cantidad perfectamente razonable de ingeniería',
    body: 'Nació en 1997, volvió a la web gracias a la ingeniería inversa de Kyutae Lee y ahora Santiago Rodríguez lo está sobreoptimizando con cuidado porque, evidentemente, el vóley de playa con Pikachu necesitaba un hogar digno en Linux.',
    original: 'Juego original: SACHI SOFT / SAWAYAKAN Programmers y Satoshi Takenouchi (1997).',
    reverse: 'Ingeniería inversa y reimplementación en JavaScript: Kyutae Lee.',
    fork: 'Linux/AppImage, experiencia de escritorio y dirección de 2.0: Santiago Rodríguez.',
    website: 'Visitar santiagorodriguez.com',
    source: 'Ver código en GitHub',
    punchline: 'Dos ratones eléctricos. Una pelota. Ningún punto lógico para detenerse.',
  },
  quit: {
    kicker: 'ESCRITORIO',
    title: 'Salir del juego',
    body: 'Cierra el AppImage y vuelve a un mundo con menos Pikachus voladores.',
    warning: 'El partido actual terminará.',
    action: 'Salir ahora',
  },
  confirmation: { title: '¿Confirmás?', accept: 'Confirmar', cancel: 'Cancelar' },
  hints: { navigate: 'Navegar', select: 'Seleccionar', back: 'Volver', change: 'Cambiar', returnToMenu: 'Volver al menú' },
  status: {
    ...EN.status,
    ready: 'Juego en pausa. Elegí una acción.',
    resumed: 'Partido reanudado.',
    restarted: 'Partido reiniciado.',
    changed: 'Configuración aplicada.',
    defaults: 'Valores predeterminados restaurados.',
    currentLanguage: 'Ese idioma ya está activo.',
    practiceScore: 'El puntaje ganador no se usa en modo práctica.',
    scoreReached: 'Ese puntaje ganador ya fue alcanzado en este partido.',
    quitUnavailable: 'Salir sólo está disponible en el AppImage de escritorio.',
  },
};

const KO = {
  ...EN,
  paused: '일시 정지',
  chip: '2.0 · 아직도 스파이크 중',
  trigger: '메뉴',
  nav: { continue: '계속', restart: '경기 다시 시작', match: '경기 설정', controls: '조작', audio: '오디오 및 그래픽', language: '언어', about: '정보', quit: '종료' },
  continue: { kicker: '경기', title: '랠리로 돌아갈까요?', body: '현재 점수와 설정 그대로 경기를 이어갑니다.', poster: '랠리를 계속하세요' },
  restart: { kicker: '경기', title: '경기 다시 시작', body: '선택한 옵션을 유지한 채 현재 대전을 처음부터 시작합니다.', warning: '점수와 라운드 진행 상황이 초기화됩니다.', action: '지금 다시 시작' },
  match: { kicker: '게임플레이', title: '경기 설정', body: '실제로 적용되는 설정입니다. 장식용 스위치는 없습니다.', winningScore: '승리 점수', speed: '게임 속도', practice: '연습 모드', reset: '기본값 복원' },
  controls: { kicker: '입력', title: '조작', body: '현재 기본 조작입니다. 전체 키 변경은 다음 단계에서 제공됩니다.', player1: '플레이어 1', player2: '플레이어 2', move: '이동', jumpDown: '점프 / 아래', powerHit: '파워 히트', pause: '일시 정지 메뉴', practiceReset: '공 초기화' },
  audio: { kicker: '표현', title: '오디오 및 그래픽', body: '원작의 개성은 유지하고 운영체제 메뉴는 덜 엽니다.', graphics: '그래픽', bgm: '배경 음악', sfx: '효과음' },
  language: { kicker: '언어', title: '언어', body: '마우스로 선택하거나 선택 키를 누른 뒤 방향키를 사용하세요.', current: '현재 언어', restartWarning: '언어를 바꾸면 앱이 다시 로드되고 현재 경기가 재시작됩니다.' },
  about: { kicker: '버전 2.0', title: '아주 합리적인 수준의 엔지니어링', body: '1997년에 태어나 Kyutae Lee의 리버스 엔지니어링으로 웹에 돌아왔고, 이제 Santiago Rodríguez가 피카츄 비치발리볼에도 제대로 된 Linux 집이 필요하다고 판단해 정성스럽게 과도한 개선을 진행하고 있습니다.', original: '원작: SACHI SOFT / SAWAYAKAN Programmers 및 Satoshi Takenouchi (1997).', reverse: 'JavaScript 리버스 엔지니어링 및 재구현: Kyutae Lee.', fork: 'Linux/AppImage, 데스크톱 UX 및 2.0 방향: Santiago Rodríguez.', website: 'santiagorodriguez.com 방문', source: 'GitHub 소스 보기', punchline: '전기 쥐 둘. 배구공 하나. 멈출 만한 합리적인 지점은 없음.' },
  quit: { kicker: '데스크톱', title: '게임 종료', body: 'AppImage를 닫고 공중의 피카츄가 더 적은 세계로 돌아갑니다.', warning: '현재 경기가 종료됩니다.', action: '지금 종료' },
  confirmation: { title: '확실합니까?', accept: '확인', cancel: '취소' },
  hints: { navigate: '이동', select: '선택', back: '뒤로', change: '변경', returnToMenu: '메뉴로 돌아가기' },
  status: { ...EN.status, ready: '게임이 일시 정지되었습니다.', resumed: '경기를 계속합니다.', restarted: '경기를 다시 시작했습니다.', changed: '설정이 적용되었습니다.', defaults: '기본 설정을 복원했습니다.', currentLanguage: '이미 선택된 언어입니다.', practiceScore: '연습 모드에서는 승리 점수를 사용하지 않습니다.', scoreReached: '현재 경기에서 이미 그 점수에 도달했습니다.', quitUnavailable: '종료는 데스크톱 AppImage에서만 사용할 수 있습니다.' },
};

const ZH = {
  ...EN,
  paused: '已暂停',
  chip: '2.0 · 仍在扣杀',
  trigger: '菜单',
  nav: { continue: '继续', restart: '重新开始比赛', match: '比赛设置', controls: '控制', audio: '音频与画面', language: '语言', about: '关于', quit: '退出' },
  continue: { kicker: '比赛', title: '回到对局？', body: '以当前比分和设置继续比赛。', poster: '继续回合' },
  restart: { kicker: '比赛', title: '重新开始比赛', body: '保留已选设置并重新开始当前对阵。', warning: '比分与回合进度将被清除。', action: '立即重新开始' },
  match: { kicker: '玩法', title: '比赛设置', body: '这些设置会真正生效，不再只是装饰。', winningScore: '获胜分数', speed: '游戏速度', practice: '练习模式', reset: '恢复默认值' },
  controls: { kicker: '输入', title: '控制', body: '这里显示当前默认按键。完整改键将在下一阶段加入。', player1: '玩家 1', player2: '玩家 2', move: '移动', jumpDown: '跳跃 / 下移', powerHit: '强力击球', pause: '暂停菜单', practiceReset: '重置球' },
  audio: { kicker: '表现', title: '音频与画面', body: '保留原作个性，同时少打开一些系统菜单。', graphics: '画面', bgm: '背景音乐', sfx: '音效' },
  language: { kicker: '语言', title: '语言', body: '可用鼠标选择，或按选择键后使用方向键。', current: '当前语言', restartWarning: '切换语言会重新载入应用并重新开始当前比赛。' },
  about: { kicker: '版本 2.0', title: '完全合理的工程投入', body: '它诞生于 1997 年，经 Kyutae Lee 的逆向工程重回网页，如今 Santiago Rodríguez 又认为皮卡丘沙滩排球理应拥有一个像样的 Linux 家园，于是继续谨慎地把事情做得略微过头。', original: '原作：SACHI SOFT / SAWAYAKAN Programmers 与 Satoshi Takenouchi（1997）。', reverse: 'JavaScript 逆向工程与重新实现：Kyutae Lee。', fork: 'Linux/AppImage、桌面体验与 2.0 方向：Santiago Rodríguez。', website: '访问 santiagorodriguez.com', source: '在 GitHub 查看源码', punchline: '两只电气鼠，一只排球，没有合理的停止点。' },
  quit: { kicker: '桌面', title: '退出游戏', body: '关闭 AppImage，回到空中皮卡丘更少的世界。', warning: '当前比赛将结束。', action: '立即退出' },
  confirmation: { title: '确定吗？', accept: '确认', cancel: '取消' },
  hints: { navigate: '导航', select: '选择', back: '返回', change: '更改', returnToMenu: '返回菜单' },
  status: { ...EN.status, ready: '游戏已暂停，请选择操作。', resumed: '比赛已继续。', restarted: '比赛已重新开始。', changed: '设置已应用。', defaults: '已恢复默认设置。', currentLanguage: '该语言已经启用。', practiceScore: '练习模式下不使用获胜分数。', scoreReached: '当前比赛已经达到该分数。', quitUnavailable: '退出功能仅在桌面 AppImage 中可用。' },
};

const STRINGS = Object.freeze({ en: EN, 'es-ar': ES, ko: KO, zh: ZH });

export function getIntegratedMenuStrings(locale) {
  return STRINGS[locale] || EN;
}
